global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'temporalmetrics'
    metrics_path: /metrics
    scheme: http
    static_configs:
      # Server metrics target
      - targets:
          # - 'host.docker.internal:8000'
          - '10.116.122.4:8000'
        labels:
          group: 'server-metrics'

      # # Local app targets (if configured)
      - targets:
           - '10.116.122.4:8077'
           - '10.116.122.4:8078'
        labels:
           group: 'sdk-metrics'
      # # Docker metrics
      # - targets:
      #     - 'host.docker.internal:9323'
      #   labels:
      #     group: 'docker-metrics'
      # Postgres Exporter
      - targets:
          - 'host.docker.internal:9187'
          - 'postgresql:9187'
        labels:
          group: 'postgres-metrics'
  - job_name: 'springbootjavasdk'
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
       - targets:
           - '10.116.122.4:3030'
         labels:
           group: 'spring-boot-metrics'